<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MAIN" Id="{c4a70cbf-fcee-40e7-9278-ab5cba9e5400}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	InputOutputConvert: InputOutputConvert;
	PID: PID;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ModbusRead();
ModbusWrite();
InputOutputConvert();
PID();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="6" Count="1" />
      <LineId Id="18" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>